name: PSScriptAnalyzer

on:
  push:
    branches: [ "main" ]
    paths:
      - "Hellbomb Script.ps1"
  pull_request:
    branches: [ "main" ]
    paths:
      - "Hellbomb Script.ps1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  PSScriptAnalyzer:
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
        with:
          path: .
          recurse: false
          includeRule: >
            PSAvoidGlobalAliases,
            PSAvoidUsingConvertToSecureStringWithPlainText,
            PSUseCompatibleCmdlets
          settings: |
            @{
              'Rules' = @{
                'PSUseCompatibleCmdlets' = @{
                    'compatibility' = @('desktop-5.1.14393.206-windows')
                }
              }
            }
          output: results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
